import type { ActionableArtifactPayload } from "@/lib/types/generative-ui";

export const SAMPLE_MENU_ENGINEERING_ARTIFACT: ActionableArtifactPayload = {
  id: "artifact-menu-eng-01",
  title: "Matrice Menu Engineering & Marges",
  type: "menu_engineering_matrix",
  version: 1,
  versionsCount: 1,
  summary: "Audit des marges brutes et répartition de 12 plats (Stars, Plowhorses, Puzzles, Dogs)",
  createdAt: new Date().toISOString(),
  isApplied: false,
  data: {
    kpis: {
      title: "Indicateurs Clés de Rentabilité Carte",
      items: [
        {
          id: "marge-moyenne",
          label: "Marge brute moyenne",
          value: 72.4,
          unit: "percent",
          deltaPercent: 3.2,
          deltaLabel: "vs mois dernier",
          isPositive: true,
          status: "optimal",
        },
        {
          id: "ticket-moyen",
          label: "Ticket moyen couvert",
          value: 48.5,
          unit: "currency",
          deltaPercent: 1.8,
          deltaLabel: "vs prévisionnel",
          isPositive: true,
          status: "optimal",
        },
        {
          id: "gain-potentiel",
          label: "Gain d'optimisation estimé",
          value: 3450,
          unit: "currency",
          deltaPercent: 8.5,
          deltaLabel: "sur 30 jours",
          isPositive: true,
          status: "optimal",
        },
      ],
    },
    chartData: {
      title: "Marge brute par catégorie de plats ($)",
      xAxisKey: "category",
      series: [
        { key: "marge", name: "Marge nette", color: "#0E7C5A" },
        { key: "cout", name: "Food cost", color: "#E07A5F" },
      ],
      points: [
        { category: "Entrées", marge: 12.5, cout: 3.2 },
        { category: "Plats Signature", marge: 28.0, cout: 8.5 },
        { category: "Pâtes & Risottos", marge: 19.5, cout: 4.1 },
        { category: "Desserts", marge: 9.8, cout: 1.9 },
        { category: "Cocktails 5à7", marge: 13.2, cout: 2.3 },
      ],
    },
    table: {
      title: "Plats Prioritaires à Réajuster",
      description: "Recommandations d'ajustement de prix selon le volume de ventes",
      columns: [
        { key: "nom", label: "Plat / Article", align: "left" },
        { key: "classification", label: "Quadrant", align: "left" },
        { key: "prixActuel", label: "Prix Actuel", align: "right", unit: "currency" },
        { key: "prixConseille", label: "Prix Recommandé", align: "right", unit: "currency" },
        { key: "margeActuelle", label: "Marge", align: "right", unit: "percent" },
      ],
      rows: [
        {
          id: "row-1",
          cells: {
            nom: "Tartare de Saumon & Yuzu",
            classification: "Star (Étoile)",
            prixActuel: 24.0,
            prixConseille: 26.0,
            margeActuelle: 76.0,
          },
          statusBadge: { label: "+2.00 $ possible", tone: "emerald" },
          actionPrompt: "Simule l'impact d'une hausse de 2$ sur le Tartare de Saumon.",
        },
        {
          id: "row-2",
          cells: {
            nom: "Burger Wagyu Signature",
            classification: "Plowhorse (Cheval de trait)",
            prixActuel: 28.5,
            prixConseille: 31.0,
            margeActuelle: 58.5,
          },
          statusBadge: { label: "Food cost élevé", tone: "amber" },
          actionPrompt: "Analyse la dérive de coût matière sur le Burger Wagyu.",
        },
        {
          id: "row-3",
          cells: {
            nom: "Risotto aux Truffes d'Été",
            classification: "Puzzle (Énigme)",
            prixActuel: 34.0,
            prixConseille: 32.0,
            margeActuelle: 81.0,
          },
          statusBadge: { label: "À promouvoir", tone: "blue" },
          actionPrompt: "Propose une stratégie pour booster les ventes du Risotto Truffes.",
        },
      ],
    },
    checklist: {
      title: "Plan d'Action Immédiat en 3 Étapes",
      estimatedTotalImpact: "+3 450 $ / mois",
      items: [
        {
          id: "task-1",
          label: "Ajuster la tarification des cocktails 5 à 7 (+1.50 $)",
          description: "Impact immédiat sans perte de volume observée sur les tables du soir.",
          priority: "haute",
          isCompleted: false,
          assignedRole: "Directeur de salle",
          estimatedImpact: "+1 200 $ / mois",
        },
        {
          id: "task-2",
          label: "Renégocier le conditionnement de la crème fleurette avec le fournisseur",
          description: "Passage aux poches de 10L pour réduire le coût unitaire de 12%.",
          priority: "moyenne",
          isCompleted: false,
          assignedRole: "Chef de cuisine",
          estimatedImpact: "+650 $ / mois",
        },
        {
          id: "task-3",
          label: "Mettre en avant le Risotto Truffes en suggestion du jour sur l'ardoise",
          description: "Augmentation attendue du taux de prise de 4% à 11%.",
          priority: "haute",
          isCompleted: true,
          assignedRole: "Service",
          estimatedImpact: "+1 600 $ / mois",
        },
      ],
    },
    alerts: [
      {
        id: "alert-1",
        severity: "warning",
        title: "Alerte Marge Burger Wagyu (-4.2%)",
        description: "Le prix du bœuf haché premium a augmenté de 8% chez le fournisseur la semaine dernière.",
        metricHighlight: "Food cost 41.5%",
        actionLabel: "Recalculer le prix",
        actionPrompt: "Calcule le prix nécessaire sur le Burger Wagyu pour maintenir 70% de marge brute.",
      },
    ],
  },
};
