/**
 * Wallet pass configuration. Callers check isXConfigured() before issuing a
 * pass so incomplete provider setup gets a clear response instead of a crash.
 */

export function isGoogleWalletConfigured() {
  return Boolean(
    process.env.GOOGLE_WALLET_ISSUER_ID &&
      (process.env.GOOGLE_WALLET_SERVICE_ACCOUNT_EMAIL || process.env.GOOGLE_WALLET_CLIENT_EMAIL) &&
      process.env.GOOGLE_WALLET_PRIVATE_KEY
  );
}

/** Apple Wallet requires a PKCS#7-signed .pkpass bundle generated by
 * lib/wallet/apple-wallet.ts with an Apple Pass Type ID certificate, its
 * matching private key, and the WWDR intermediate certificate.
 */
export function isAppleWalletConfigured() {
  return Boolean(
    process.env.APPLE_WALLET_TEAM_ID &&
      process.env.APPLE_WALLET_PASS_TYPE_ID &&
      process.env.APPLE_WALLET_SIGNER_CERT &&
      process.env.APPLE_WALLET_SIGNER_KEY &&
      process.env.APPLE_WALLET_WWDR_CERT
  );
}
